<?php

/**
 * BlogPostImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPostImage');
    }
}