<?php

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page extends BasePage
{
  /**
   * return page name + formatted date
   */
  public function getPageNameWithDate()
  {
    return $this->get('name').', from: '.date_format(new DateTime($this->get('updated_at')), 'd.m.Y');
  }
  
  // Andy Johnson, AKA "Buss" 
  // function getFullName()
  
}
