<?php

/**
 * PartnersTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartnersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartnersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partners');
    }
}