# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sf_captchagd:
#    image_width:                100 # image width in pixels
#    image_height:               30 # image height in pixels
#    chars:                      "123456789" # possible chars in captcha
#    length:                     4 # length of captcha
#    font_size:                  18 # font size
    force_new_captcha:          true
