<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'network', 'string', '255', array(
             ));
        $this->addColumn('sf_guard_user', 'identity', 'string', '255', array(
             ));
        $this->addColumn('sf_guard_user', 'uid', 'string', '255', array(
             ));
        $this->addColumn('sf_guard_user', 'profile', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'network');
        $this->removeColumn('sf_guard_user', 'identity');
        $this->removeColumn('sf_guard_user', 'uid');
        $this->removeColumn('sf_guard_user', 'profile');
    }
}