<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('blog_comment', 'root_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('blog_comment', 'root_id');
    }
}