<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('blog_post_image', 'blog_post_image_blog_post_id_blog_post_id', array(
             'name' => 'blog_post_image_blog_post_id_blog_post_id',
             'local' => 'blog_post_id',
             'foreign' => 'id',
             'foreignTable' => 'blog_post',
             ));
        $this->addIndex('blog_post_image', 'blog_post_image_blog_post_id', array(
             'fields' => 
             array(
              0 => 'blog_post_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('blog_post_image', 'blog_post_image_blog_post_id_blog_post_id');
        $this->removeIndex('blog_post_image', 'blog_post_image_blog_post_id', array(
             'fields' => 
             array(
              0 => 'blog_post_id',
             ),
             ));
    }
}