<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('blog_post_image', 'filename', 'string', '255', array(
             ));
    }

    public function down()
    {

    }
}