<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('blog_post_image', 'content');
        $this->addColumn('blog_post_image', 'filename', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('blog_post_image', 'content', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->removeColumn('blog_post_image', 'filename');
    }
}