Page:
  actAs:
    Timestampable: ~
  columns:
    id:       { type: integer(4), primary: true, autoincrement: true }
    name:     { type: string(255), notnull: true }
    slug:     { type: string(255) }
    pic:      { type: string(255) }
    content:  { type: clob, notnull: true }

News:
  actAs:
    Timestampable: ~
  columns:
    id:       { type: integer(4), primary: true, autoincrement: true }
    title:    { type: string(255), notnull: true }
    content:  { type: string(255), notnull: true }
    is_enabled: { type: boolean }

FeedBack:
  actAs:
    Timestampable: ~
  columns:
    id:       { type: integer(4), primary: true, autoincrement: true }
    email:    { type: string(255), notnull: true }
    phone:    { type: string(255), notnull: false }
    content:  { type: string(255), notnull: true }

Question:
  actAs:
    Timestampable: ~
  columns:
    id:       { type: integer(4), primary: true, autoincrement: true }
    question:  { type: string(255), notnull: true }
    answer:  { type: string(255) }
